# List of issues to include in the synthetic data
issues = [
    "Financial disagreements (e.g., spending habits, debt, child support payments).",
    "Division of household responsibilities (e.g., chores, maintenance).",
    "Communication breakdowns (e.g., lack of communication, misunderstandings).",
    "Trust issues (e.g., infidelity, suspicion, jealousy).",
    "Differences in parenting styles or decisions.",
    "Time management and scheduling conflicts (e.g., visitation schedules, personal time).",
    "Personal boundaries and respect for privacy.",
    "Extended family involvement (e.g., in-laws, family obligations).",
    "Social life and friendships (e.g., differing social circles, time spent with friends).",
    "Emotional support and empathy (e.g., lack of emotional support, neglect).",
    "Career or job-related stress and decisions.",
    "Relocation or living arrangements (e.g., moving cities, living apart).",
    "Health and wellness issues (e.g., disagreements about medical decisions, lifestyle choices).",
    "Substance abuse or addiction problems.",
    "Legal issues (e.g., divorce proceedings, custody battles).",
    "Shared custody of children.",
    "Differing future goals and aspirations.",
    "Handling of past conflicts and unresolved issues.",
    "Intimacy and sexual compatibility.",
    "Vacations and leisure activities (e.g., differing interests, planning conflicts).",
    "Child discipline and education decisions.",
]
